[package]
name = "safhe_house"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
pyo3 = {version = "0.22.2", features = ["extension-module"] } 
num = "0.4.3"

[[test]]
name = "bfv_tests" 
path = "src/tests/bfv_tests.rs" 